jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Uvweb\UvBundle\Entity\User:
            algorithm:        sha512
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Uvweb\UvBundle\Entity\User, property: identity }
        web_service:
            entity: { class: Uvweb\UvBundle\Entity\User, property: identity }


    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/logout, roles: ROLE_USER }
        - { path: ^/sflogin, roles: ROLE_USER }
        - { path: ^/post, roles: ROLE_USER }
        - { path: ^/user/edit, roles: ROLE_USER }
        - { path: ^/migration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/forgottenaccount, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/setuvdefinitions, roles: ROLE_ADMIN }
        - { path: ^/uv/app/comment, roles: ROLE_USER, methods: [PUT] }
        - { path: ^/uv/app/comment/cancomment, roles: ROLE_USER }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        uvweb:
            pattern: ^/uv/app/comment
            stateless: true
            http_basic:
                provider: web_service

        main:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: uvweb_login
                check_path: sf_login
            logout:
                path:       uvweb_logout
                target:     /

            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
