#Setting uv definitions
uvweb_uv_setuvdefinitions:
    path: /setuvdefinitions
    defaults:  { _controller: UvwebUvBundle:Home:setUvDefinitions }

uvweb_uv_list:
    path: /uv/all/{order}
    defaults:  { _controller: UvwebUvBundle:Detail:listAll, order: 'name' }
    requirements:
        order: "name|rate"

uvweb_uv_catalog:
    path: /uv/catalog
    defaults:  { _controller: UvwebUvBundle:Detail:catalog}

uvweb_uv_list_category:
    path: /uv/{category}/{order}
    defaults:  { _controller: UvwebUvBundle:Detail:listCategory, order: 'name' }
    requirements:
        category: "gb|gi|gm|gp|gsm|gsu|tsh|tc|master|doctorat"
        order: "name|rate|dynamic"

uvweb_uv_nameslike:
    path: /uv/like
    defaults: { _controller: UvwebUvBundle:Home:getUvNamesLike }

uvweb_uv_detail:
    path: /uv/{uvname}
    defaults:  { _controller: UvwebUvBundle:Detail:detail, uvname: '' }

uvweb_uv_newpost:
    path: /post/{uvname}
    defaults:  { _controller: UvwebUvBundle:Detail:post }

uvweb_uv_editcomment:
    path: /user/edit/comment/{commentid}
    defaults:  { _controller: UvwebUvBundle:Profile:editComment }
    requirements:
        commentid: \d+

uvweb_uv_homepage:
    path:  /
    defaults: { _controller: UvwebUvBundle:Home:index }

uvweb_uv_about:
    path:   /about
    defaults:  { _controller: UvwebUvBundle:Home:about }

#Profile paths
uvweb_user_add:
    pattern: /user/register
    defaults: { _controller: UvwebUvBundle:Profile:addUser }

uvweb_uv_profile:
    pattern: /user/{userid}
    defaults: { _controller: UvwebUvBundle:Profile:display }
    requirements:
        userid:  ^[0-9]+$

uvweb_login:
    pattern: /login
    defaults: { _controller: UvwebUvBundle:Profile:login }

uvweb_migration:
    pattern: /migration
    defaults: { _controller: UvwebUvBundle:Profile:migration }

uvweb_forgottenaccount:
    pattern: /forgottenaccount
    defaults: { _controller: UvwebUvBundle:Profile:forgottenAccount }

uvweb_user_edit:
    pattern: /user/edit/{userid}
    defaults: { _controller: UvwebUvBundle:Profile:editUser }
    requirements:
        userid: \d+

#Admin paths
uvweb_admin_home:
    pattern: /admin
    defaults: { _controller: UvwebUvBundle:Admin:home }

uvweb_admin_comment_validate:
    pattern: /admin/validatecomment/{commentid}
    defaults: { _controller: UvwebUvBundle:Admin:validateComment }
    requirements:
        commentid: \d+

uvweb_admin_comment_refuse:
    pattern: /admin/refusecomment/{commentid}
    defaults: { _controller: UvwebUvBundle:Admin:refuseComment }
    requirements:
        commentid: \d+

uvweb_admin_add_news:
    pattern: /admin/news/add
    defaults: { _controller: UvwebUvBundle:Admin:addNews }

uvweb_admin_edit_news:
    pattern: /admin/news/edit/{newsid}
    defaults: { _controller: UvwebUvBundle:Admin:editNews }
    requirements:
        newsid: \d+

uvweb_admin_delete_news:
    pattern:   /admin/news/delete/{newsid}
    defaults:  { _controller: UvwebUvBundle:Admin:deleteNews }
    requirements:
        newsid: \d+

#Authentication paths
sf_login:
    pattern: /sflogin

uvweb_logout:
    pattern: /logout

#Web Service paths
uvweb_uv_recentactivity:
    path: /app/recentactivity
    defaults:  { _controller: UvwebUvBundle:WebService:recentActivity }
    requirements:
        _method: GET